### ISSUE TITLE
Feature Request: please add org.eclipse.jdt.annotation

### ISSUE THREAD

**Issue by tg-freigmbh** [gradlex-org/java-module-dependencies#144]
Please add 
org.eclipse.jdt.annotation ->org.eclipse.jdt:org.eclipse.jdt.annotation
https://mvnrepository.com/artifact/org.eclipse.jdt/org.eclipse.jdt.annotation/2.3.0
already has an Automatic-Module-Name

**Comment by jjohannes** [comment]
Thanks. It will be in the next release. If you have more cases in the future, feel free to directly open a PR against [main/src/main/resources/org/gradlex/javamodule/dependencies/modules.properties](https://github.com/gradlex-org/java-module-dependencies/blob/main/src/main/resources/org/gradlex/javamodule/dependencies/modules.properties).
