### ISSUE TITLE
[doc][question][feature?] - in libs.versions.toml?

### ISSUE THREAD

**Issue by xenoterracide** [gradlex-org/java-module-dependencies#82]
I've been using `-`, not `_` in my `libs.versions.toml`. It seems to be the [default recommendation](https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml) is it not supported? please improve the [documentation](https://github.com/gradlex-org/java-module-dependencies?tab=readme-ov-file#define-module-versions-in-a-version-catalog) as part of answer. If it's not, maybe also add feature.

**Comment by jjohannes** [comment]
Yes this works as Gradle automatically replaces both `_` and `-` with `.`. I added a test to confirm this and added a note about the notations in TOML to the Readme.
